### ISSUE TITLE
[GIP] Phase out GoChain Proxy Nodes on Network

### ISSUE THREAD

**Issue by AnonHODLer** [gochain/gips#31]
## Summary
Proposal to phase out the GoChain and GoPath nodes from the Proof of Reputation consensus.

## Why
It's been 2.5 years and the GoChain blockchain has grown a strong network on nodes including Lenovo, DISH, Conservation Intl, Penn State and more. In total there are 19 nodes run by 14 organizations. https://explorer.gochain.io/signers?signers_tab=monthly

Currently, GoChain operates 5 nodes on the network (4 labeled GoChain and 1 labeled GoPath). These nodes helped bootstrap the network when it first launched. The network has enough nodes now that bootstrapping isn't needed. Keeping the GoChain proxy nodes on the network is no longer needed. In fact, having more than 25% of the PoR nodes run by GoChain makes the governance less decentralized.

Also, the GoChain nodes recently sold 10m GO to Binance. They're meant to reward the companies, non profits, and organizations that risk their reputations to secure our PoR network.

Shutting down the GoChain nodes and sending their funds to the treasury will:
1. Increase the decentralization of the governance
2. Increase the average reputation of the network
3. Provide the organizations with their full share of node rewards
4. Add tokens to the treasury

## Specification
Remove the GoChain nodes as signers on the network. Take all remaining rewards that those nodes have earned (23,719,129 GO) and send them to the treasury.

## Additional Information
List of nodes: https://explorer.gochain.io/signers?signers_tab=daily
There are 5 GoChain proxy nodes. All 5 nodes send their rewards to 2 consolidated wallets: 

Wallet 1: Received 13,361,316 GO, Sold 0 GO.
https://explorer.gochain.io/addr/0xE12d1FD4B38bd9a162650d35FeC83d5105aD4b41

Wallet 2: Received 20,357,813 GO, Sold 10,000,000 GO.
https://explorer.gochain.io/addr/0x65a0e277B2d0eEF62b8C30b280B4C49f83a104d3

**Comment by jmank88** [comment]
I'm not sure if there is some confusion or just mixed terms, but for clarity the term _proxy node_ actually refers to nodes serving https://rpc.gochain.io, our RPC proxy service. The _proxy nodes_ are listed on https://stats.gochain.io, but do not have signing rights.

**Comment by AnonHODLer** [comment]
> I'm not sure if there is some confusion or just mixed terms, but for clarity the term _proxy node_ actually refers to nodes serving https://rpc.gochain.io, our RPC proxy service. The _proxy nodes_ are listed on https://stats.gochain.io, but do not have signing rights.

This proposal is referring to the 5 GoChain nodes that are signing:
GoChain: 0xed7f2e81b0264177e0df8f275f97fd74fa51a896
GoChain: 0xf6290b7f9f871d21317acc259f2ae23c0aa69c73
GoChain: 0x3ad14430951aba12068a8167cebe3ddd57614432
GoChain: 0x3729d2e93e8037f87a2c9afe34cb84b7069e4dea
GoPath: 0xf7678aa7f42bc017f3d6011ca27aed400647960d

**Comment by AnonHODLer** [comment]
It's disappointing to see the CTO of the project downvote a proposal that would result in further decentralization of the PoR consensus. This proposal is designed to limit the centralized power that GoChain currently exercises and force more transparency.
![image](https://user-images.githubusercontent.com/73446356/97311371-a926e380-183a-11eb-83c0-ceacb591c4c2.png)

**Comment by judgementdey** [comment]
The resistance from the CTO shows the intention of Gochain to maintain control. Disappointing but not a surprise.

**Comment by intangible78** [comment]
Why? doesnt cto has a right to downvote? Imo good example of decentralization

**Comment by judgementdey** [comment]
> Why? doesnt cto has a right to downvote? Imo good example of decentralization

It isnt that the CTO has voted that has been taken as an issue but what he has voted for (which is to maintain control of network with team nodes).
