### ISSUE TITLE
[GIP] Hold regular meetings with signer nodes and share minutes

### ISSUE THREAD

**Issue by judgementdey** [gochain/gips#32]
## Summary
GoChain is sold on its consensus mechanism Proof of Reputation, Make that activity transparent or drop the PoR rhetoric.

## Why
Currently the PoR mechanism is not visible to the community as a functioning model. This damages confidence in the network and relies on GoChain reputation which is not sufficient to represent 50 PoR signer nodes. If PoR exists as defined there should be regular FORMAL engagement with all nodes. It should be simple to publish the minutes to those meetings and vote outcomes. 

## Specification
Simply share the ongoing engagement that should be in place at this time with all the nodes. If each node is actually staking their reputation then they will be supporting GoChain, getting regular reports and voting on key decisions (such as adding nodes, implementing Governance etc). That includes the new Governance methodology that has been recently added that appears to have no transparency around node activity and votes.

## Additional Information
This is simply a request for transparency for all to ensure that GoChain is not the dictator and PoR is in place and functioning as designed. If until 50 nodes are in place GoChain actually intend to run the chain as their own centralised system they should remove the PoR labels within website and be transparent with their intentions. You cant say the chain is run on PoR when it isn't!

**Comment by taci4min** [comment]
no wonder the reaction of the CEO, not at all ...

**Comment by AnonHODLer** [comment]
This doesn't seem feasible. I support more transparency, but if you've ever worked in a startup (I have), it's not realistic to a assume they'd have the bandwidth to compile minutes, redact sensitive info, and release them.

**Comment by judgementdey** [comment]
> This doesn't seem feasible. I support more transparency, but if you've ever worked in a startup (I have), it's not realistic to a assume they'd have the bandwidth to compile minutes, redact sensitive info, and release them. For that reason, I have to give this a 👎

its a fair point that the overhead would be greater but considering these meetings would be around the governance and oversight of the chain based on those node signers being considerate to their reputation there has to be some form of summary of the outcomes. All I am asking is that they are shared.

**Comment by AnonHODLer** [comment]
> > This doesn't seem feasible. I support more transparency, but if you've ever worked in a startup (I have), it's not realistic to a assume they'd have the bandwidth to compile minutes, redact sensitive info, and release them. For that reason, I have to give this a 👎
> 
> its a fair point that the overhead would/could be greater but considering these meetings would be around the governance and oversight of the chain based on those node signers being considerate to their reputation there has to be some form of summary of the outcomes. All I am asking is that they are shared.

My guess is that node voting in governance proposals will be on-chain for transparency reasons. For instance, if the nodes colluded and voted to issue more tokens, or to change a previous block on the network, it would be recorded and their reputation would be tarnished and they'd likely be sued in court.

Signing blocks is already recorded on chain.

Any other discussions, I feel like are ok to be kept private. Bitcoin miners don't have to publish all of their conversations.

**Comment by judgementdey** [comment]
The issue with this is there is zero PoR assurance in place currently. I agree that voting should be on chain but as there isnt and there is absolutely nothing to provide transparency that PoR actually is in place, there should be some interim process prior to gaining 50 nodes that provides a level of assurance that PoR is even a thing. Right now I dont even think more than 3 people in Lenovo (or other signers) know about GoChain, let alone staking their entire reputation on it. That needs to change or PoR needs to stop being the consensus mechanism that the team place in the spotlights.
